### PR TITLE
Fix buttons in loops

### LINKED ISSUE #592: Buttons Not Working In Loops
The 'Page Navigation',  'Submit' & 'Add Record' buttons do not work within a Loop component. When selected the page refreshes.

### PR DESCRIPTION
**Pull request by chipit24**
Fixes #592.

The fix for this is described at https://github.com/ProcessMaker/screen-builder/issues/592#issuecomment-592125989.

### CODE REVIEW

File: src/components/renderer/form-loop.vue [hunk 1]
```diff
@@ -1,18 +1,16 @@
 <template>
   <div class="form-group">
-    <div v-for="loopIndex in times" :key="loopIndex">
-      <form>
```
Comment (chipit24) [inline src/components/renderer/form-loop.vue]: This `form` element was the cause of the issue. Because nested buttons didn't specify a `type`, they defaulted to `"submit"`, causing this form to submit and reload the page.

I also moved the `v-for` from the `div` to `vue-form-renderer` and removed that redundant `div`.

File: src/components/renderer/form-loop.vue [hunk 2]
```diff
@@ -1,18 +1,16 @@
...
+      v-for="loopIndex in times"
+      :key="loopIndex"
+      :data="getMatrixValue(loopIndex)"
+      :config="rendererConfig"
+      :computed="null"
+      :custom-css="null"
+      :watchers="null"
+      @submit="submit"
+      @update="setMatrixValue(loopIndex, $event)"
+    />
```
Comment (chipit24) [inline src/components/renderer/form-loop.vue]: I didn't change any of the props here, I re-arranged them to group bindings/props data and events.

**Comment by sanjacornelius** [comment]
@chipit24  Submit & the Record List 'Add Record' button works but the 'Page Navigation' button is still having issues. The button no longer refreshes the page but now it doesn't load the configured page.

<a href="https://www.loom.com/share/30b1ef2989434928b595c9c711499543"> <p>27 February, 2020 - Loom Recording - Watch Video</p>  </a>

**Comment by nolanpro** [comment]
@chipit24 individual iterations were in their own `<form>` element because that was the only way I could isolate radio groups. Do you know a better way? Try adding a select list and set it to render as radio buttons. Make sure they can operate independently in each loop iteration.

**Comment by chipit24** [comment]
@sanjacornelius I swear I tested with navigation buttons but I guess I missed that :O I'll look into what's going on there.

And thanks @nolanpro! I'll test with radio buttons and update my PR. I may be able to catch the submit in the form and `preventDefault`.

**Comment by chipit24** [comment]
@sanjacornelius @nolanpro Radio and navigation buttons should now be fixed.
