### PR TITLE
Set default values for variables

### LINKED ISSUE #351: Default Values
All variables should have a default value. This will guarantee that the variable is always available, even if it is set to null. 

Special case: Date / Time picker should default to NOW

If you submit a form the data object should contain the variable with no value. 

This is wrong:

image

this is correct

image

### PR DESCRIPTION
**Pull request by sanjacornelius**
closes #351 

**Issue:**
Data preview does not display variables with the value of null.

**Fix:**
This PR runs the 'setDefaultValues' method to display the variable's default value in the data preview.

Screen Shot 2019-10-07 at 2 40 30 PM

### CODE REVIEW

File: src/components/vue-form-renderer.vue [hunk 1]
```diff
@@ -299,6 +300,11 @@ export default {
         defaultValue = [];
       }
 
+      if (item.component === 'FormDatePicker') {
+        let date = new Date();
```
Comment (chipit24) [inline src/components/vue-form-renderer.vue]: Since you're not re-assigning `date`, you can use `const` instead of `let`.

Comment (sanjacornelius) [reply src/components/vue-form-renderer.vue]: New commits include removing the `defaultValues` data key and updating `let` to `const` for the `date` variable. 😃
