### PR TITLE
Nested submit button does nothing

### LINKED ISSUE #559: Nested submit button does nothing
**Steps to Reproduce:**

Have a screen with another screen nested in

Have the nested screen use a submit button

Run the screens

Press on the nested submit button

**Current Behavior:**

The button does nothing

Expected Behavior:

Remove / Hide submit button in the nested screen

https://www.dropbox.com/s/opzt2x35p5s5l5d/nestedSubmit.mp4?dl=0

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
closes #559 

## Changes
- Hide submit buttons on nested screen.

### CODE REVIEW

File: src/components/renderer/form-nested-screen.vue [hunk 1]
```diff
@@ -54,21 +54,41 @@ export default {
     },
   },
   methods: {
+    elementsValid(config) {
```
Comment (chipit24) [inline src/components/renderer/form-nested-screen.vue]: The name `elementsValid` doesn't really communicate anything to me. Since this function is hiding all submit buttons, I think a name like `hideSubmitButtons` would communicate intent much better.

File: src/components/renderer/form-nested-screen.vue [hunk 2]
```diff
@@ -54,21 +54,41 @@ export default {
...
+          this.elementsValid(item);
+        }
+
+        //If the element has items
+        if (item.items) {
+          this.elementsValid(item.items);
+        }
+
+        //hidden buttons
+        if (item.config && item.component === 'FormButton' && item.config.event === 'submit') {
```
Comment (chipit24) [inline src/components/renderer/form-nested-screen.vue]: Instead of having a comment (which is confusing, since it's not explaining what this block is even doing, but simply stating "hidden buttons"), I think it would be much more readable to break out the conditional into a function. Something like:

```js
if (this.isSubmitButton(item)) {
  item.config.hidden = true;
}
```

File: src/components/renderer/form-nested-screen.vue (hunk 1 above)
Comment (marcoAntonioNina) [reply src/components/renderer/form-nested-screen.vue]: applied change

File: src/components/renderer/form-nested-screen.vue (hunk 2 above)
Comment (marcoAntonioNina) [reply src/components/renderer/form-nested-screen.vue]: applied change
