### PR TITLE
Fix record list

### LINKED ISSUE #297: Record List Fails
The record form control doesn't allow additions to the form.

https://www.dropbox.com/s/ocu66udkl5kmkgt/recordformserror.mov?dl=0

```
vendor.js?id=b00b43960daef9090f5c:64269 [Vue warn]: Error in v-on handler: "TypeError: Cannot set property 'currentPage' of undefined"

found in

---> <FormRecordList>
       <VueFormRenderer>
         <TaskScreen> at resources/js/tasks/components/TaskForm.vue
           <Root>
```

### PR DESCRIPTION
**Pull request by chipit24**
Fixes #297.

Video of fix: https://www.dropbox.com/s/ftaoku8ulcwtj0p/record_list_working_02.mov?dl=0.

### CODE REVIEW

File: src/components/renderer/form-record-list.vue [hunk 1]
```diff
@@ -43,6 +43,7 @@
     </template>
 
     <b-modal
+      :static="true"
```
Comment (chipit24) [inline src/components/renderer/form-record-list.vue]: This was required due to a change in bootstrap-vue modal:
> CHANGED in 2.0.0-rc.20 Modals will not render their content in the document until they are shown (lazily rendered). https://bootstrap-vue.js.org/docs/components/modal/#lazy-loading-and-static-modals
